default_datasets:
- eu
- us
- asia_east1
- asia_east2
- asia_northeast1
- asia_northeast2
- asia_northeast3
- asia_south1
- asia_southeast1
- australia_southeast1
- europe_north1
- europe_west1
- europe_west2
- europe_west3
- europe_west4
- europe_west6
- northamerica_northeast1
- southamerica_east1
- us_central1
- us_east1
- us_east4
- us_west1
- us_west2
default_datasets_for_test:
- test_eu
- test_us
- test_asia_east1
- test_asia_east2
- test_asia_northeast1
- test_asia_northeast2
- test_asia_northeast3
- test_asia_south1
- test_asia_southeast1
- test_australia_southeast1
- test_europe_north1
- test_europe_west1
- test_europe_west2
- test_europe_west3
- test_europe_west4
- test_europe_west6
- test_northamerica_northeast1
- test_southamerica_east1
- test_us_central1
- test_us_east1
- test_us_east4
- test_us_west1
- test_us_west2
default_gcp_project: bigfunctions
default_gcp_project_for_test: bigfunctions
