site_name: BigFunctions
site_description: 'Supercharge BigQuery with BigFunctions.'
site_url: 'https://unytics.io/bigfunctions/'
repo_name: 'unytics/bigfunctions'
repo_url: 'https://github.com/unytics/bigfunctions'
edit_uri: 'edit/main/site/content'
copyright: 'Copyright &copy; 2022 Unytics'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: site/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - tabs
    - content.tabs.link
    - instant
    # - toc.integrate
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.hide
    - navigation.expand

markdown_extensions:
  - attr_list
  - tables
  - toc:
      toc_depth: 4
      permalink: "¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins: []
nav:
  - Home: index.md
  - BigFunctions: reference/index.md
  - Getting Started:
    - getting_started/index.md

