name: Suggest a New BigFunction
description: The sky is the limit. Suggest anything that could help data-people.
title: "[new]: `function_name(argument1, argument2)`"
labels: ["new-bigfunction"]
body:
  - type: markdown
    attributes:
      value: |
        🙏 **Thanks for taking the time to suggest a new BigFunction!**. ⚠️ Before going further, check in the [list of existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Anew-bigfunction) if your idea has not already been suggested. If it has, please don't create a new issue but add a comment on the existing one such as `+1` to upvote it. 
  - type: textarea
    id: description
    attributes:
      label: BigFunction Description as it would appear in the documentation
      description: Give the description of the function as it should appear on the [BigFunctions website](https://unytics.io/bigfunctions/reference/).
      placeholder: Example for `is_email_valid` --> Returns true if email is valid
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
