name: deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: pip install pyyaml
      - run: python bigfun/build_js_libs.py --generate-js-libs-package-json
      - run: npm install
      - run: python bigfun/build_js_libs.py --generate-webpack-configs
      - run: npm run-script build-all-libs
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - run: gsutil cp js_builds/* gs://bigfunctions_js_libs/
