name: deploy pages
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.4.0 mkdocs-material==8.5.6 mkdocs-material-extensions==1.0.3 pyyaml Jinja2
      - run: python bigfun/generate_doc.py
      - run: mkdocs gh-deploy --force
